default: build

build:
	javac Game.java

all:
	javac Game.java
	javac BasicEnemy.java
	javac FastEnemy.java
	javac GameObject.java
	javac Handler.java
	javac HUD.java
	javac ID.java
	javac KeyInput.java
	javac Menu.java
	javac MenuEffect.java
	javac Player.java
	javac Spawn.java
	javac Trail.java
	javac Window.java

run: build
	java Game

clean:
	DEL /Q *.class
